# Generated by Django 4.2.4 on 2023-08-20 05:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilites",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
