# Generated by Django 4.2.4 on 2023-08-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0002_alter_healthfacilites_geom"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="healthfacilites",
            index=models.Index(fields=["geom"], name="geom_index"),
        ),
    ]
