# Generated by Django 4.2.4 on 2023-08-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0003_healthfacilites_geom_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilites",
            name="amenity",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilites",
            name="healthcare",
            field=models.CharField(max_length=167, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilites",
            name="name",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilites",
            name="operatorty",
            field=models.CharField(max_length=80, null=True),
        ),
    ]
